/** Static industry roster for the Lead Finder filters — matches the brief's exact list. */
export const INDUSTRIES: string[] = [
  "Healthcare",
  "Hospitals",
  "Clinics",
  "Education",
  "Schools",
  "Universities",
  "Manufacturing",
  "Retail",
  "Finance",
  "Banking",
  "Insurance",
  "Construction",
  "Real Estate",
  "Government",
  "Logistics",
  "Transportation",
  "Hotels",
  "Restaurants",
  "Travel",
  "Legal",
  "IT",
  "Software",
  "SaaS",
  "Agencies",
  "Telecom",
  "Energy",
  "Automotive",
  "NGO",
];
