// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { defineConfig } from "prisma/config";

try {
  // dotenv is a devDependency, only needed to load a local .env file for
  // host/CI runs of the Prisma CLI. It's intentionally absent from the
  // production image (see docker-compose.yml's note on why `prisma migrate
  // deploy` runs from the host, not inside that container), where real env
  // vars are already set by the process environment.
  // eslint-disable-next-line @typescript-eslint/no-require-imports -- must be synchronous so DATABASE_URL below is populated before defineConfig runs; a dynamic import() would resolve too late.
  require("dotenv/config");
} catch {}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
