import Link from "next/link";
import { ArrowRight } from "lucide-react";

import { Container } from "@/components/ui/container";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from "@/components/ui/accordion";
import { prisma } from "@/lib/prisma";
import { requirePlatformOwner } from "@/lib/billing/platform-admin";
import type { ComplianceFramework } from "@/generated/prisma/client";
import type { ComplianceFindings } from "@/lib/security/compliance";
import { RegenerateReportButton } from "./_components/regenerate-report-button";

const FRAMEWORKS: ComplianceFramework[] = ["SOC2", "ISO27001", "GDPR", "CCPA", "DPDP_INDIA", "PCI_DSS", "WCAG"];

const FRAMEWORK_LABEL: Record<ComplianceFramework, string> = {
  SOC2: "SOC 2",
  ISO27001: "ISO/IEC 27001",
  GDPR: "GDPR",
  CCPA: "CCPA",
  DPDP_INDIA: "DPDP (India)",
  PCI_DSS: "PCI DSS",
  WCAG: "WCAG",
};

const STATUS_VARIANT: Record<string, "default" | "secondary" | "outline" | "accent"> = {
  READY: "accent",
  PARTIAL: "outline",
  NOT_READY: "secondary",
};

function formatDateTime(date: Date): string {
  return date.toLocaleString("en-US", { month: "short", day: "numeric", year: "numeric", hour: "2-digit", minute: "2-digit" });
}

function isComplianceFindings(value: unknown): value is ComplianceFindings {
  return (
    typeof value === "object" &&
    value !== null &&
    Array.isArray((value as { controls?: unknown }).controls)
  );
}

/**
 * Platform-operator-only compliance readiness dashboard. Real
 * ComplianceReport rows (prisma/schema.prisma's "Final Phase: Enterprise
 * Security, Monitoring, DR, Compliance" section) generated by
 * generateComplianceReport() (src/lib/security/compliance.ts) — an HONEST
 * report, never a fabricated certification. See that file's top comment for
 * exactly what is/isn't verified from code.
 */
export default async function AdminCompliancePage() {
  await requirePlatformOwner("/admin/compliance");

  const reports = await prisma.complianceReport.findMany({ orderBy: { generatedAt: "desc" } });
  const latestByFramework = new Map<ComplianceFramework, (typeof reports)[number]>();
  for (const report of reports) {
    if (!latestByFramework.has(report.framework)) latestByFramework.set(report.framework, report);
  }

  return (
    <Container className="flex flex-col gap-6 py-8">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div>
          <h1 className="text-2xl font-semibold text-foreground">Compliance Readiness</h1>
          <p className="max-w-3xl text-sm text-muted-foreground">
            A real, honest architectural-readiness snapshot per framework — never a fabricated certification. Every
            control below is either checked live against this codebase (a database round-trip, a live crypto/TOTP/rate-
            limiter test, a source-file scan) or explicitly marked as an operational/manual control that no code can
            verify. A real SOC2/ISO27001 certification or PCI DSS attestation still requires a third-party auditor.
          </p>
        </div>
        <div className="flex shrink-0 flex-wrap gap-x-4 gap-y-1.5">
          {[
            { href: "/admin/compliance/risks", label: "Security Risk Register" },
            { href: "/admin/compliance/policies", label: "Policy Center" },
            { href: "/admin/compliance/vendors", label: "Vendor Register" },
            { href: "/admin/compliance/assets", label: "Asset Inventory" },
            { href: "/admin/compliance/soa", label: "Statement of Applicability" },
            { href: "/admin/compliance/changes", label: "Change Management" },
          ].map((link) => (
            <Link key={link.href} href={link.href} className="flex items-center gap-1.5 text-sm font-medium text-primary hover:underline">
              {link.label} <ArrowRight className="size-3.5" />
            </Link>
          ))}
        </div>
      </div>

      <div className="grid gap-6">
        {FRAMEWORKS.map((framework) => {
          const report = latestByFramework.get(framework);
          const findings = report && isComplianceFindings(report.findings) ? report.findings : null;

          return (
            <Card key={framework} glass>
              <CardHeader>
                <div className="flex flex-wrap items-center justify-between gap-3">
                  <div>
                    <CardTitle>{FRAMEWORK_LABEL[framework]}</CardTitle>
                    <CardDescription>
                      {report
                        ? `Last generated ${formatDateTime(report.generatedAt)}`
                        : "No report generated yet."}
                    </CardDescription>
                  </div>
                  <div className="flex items-center gap-3">
                    {report && <Badge variant={STATUS_VARIANT[report.status] ?? "outline"}>{report.status}</Badge>}
                    <RegenerateReportButton framework={framework} />
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                {!findings ? (
                  <p className="text-sm text-muted-foreground">
                    Click &ldquo;Regenerate&rdquo; to run this framework&apos;s real, live control checks.
                  </p>
                ) : (
                  <div className="flex flex-col gap-4">
                    <p className="text-xs text-muted-foreground">{findings.disclaimer}</p>
                    <p className="text-xs text-muted-foreground">
                      Code-verifiable controls passed: {findings.codeControlsPassed} / {findings.codeControlsTotal}. {findings.statusRule}
                    </p>
                    <Accordion type="multiple" className="rounded-lg border border-border">
                      {findings.controls.map((control, index) => (
                        <AccordionItem key={`${control.name}-${index}`} value={`${framework}-${index}`} className="px-4 last:border-b-0">
                          <AccordionTrigger>
                            <span className="flex flex-wrap items-center gap-2 text-left">
                              <Badge variant={control.verified ? "accent" : "secondary"}>
                                {control.verified ? "Verified" : "Not verified"}
                              </Badge>
                              <Badge variant="outline">{control.verificationMethod}</Badge>
                              <span>{control.name}</span>
                            </span>
                          </AccordionTrigger>
                          <AccordionContent>{control.detail}</AccordionContent>
                        </AccordionItem>
                      ))}
                    </Accordion>
                  </div>
                )}
              </CardContent>
            </Card>
          );
        })}
      </div>
    </Container>
  );
}
